### ISSUE TITLE
Inject build-time variables

### ISSUE THREAD

**Issue by dtan4** [dtan4/paus#10]
## WHY

Some Dockerfiles require to inject build-time variables. For example, fetching private repository from GitHub requires `GITHUB_ACCESS_TOKEN`.

``` dockerfile
FROM ruby:2.3.0-slim
MAINTAINER Daisuke Fujita <dtanshi45@gmail.com> (@dtan4)

ARG GITHUB_ACCESS_TOKEN

# ...

RUN git clone https://$GITHUB_ACCESS_TOKEN:x-oauth-basic@github.com/dtan4/privaterepo
```

``` bash
$ docker build --build-arg GITHUB_ACCESS_TOKEN=githubtoken ,
```

`docker-compose.yml`:

``` yaml
version: '2'
services:
  web:
    build:
      context: .
      args:
        - "GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}"
    ports:
      - 3000:3000
    links:
      - elasticsearch:elasticsearch
      - redis:redis
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
```
## WHAT

As environment variable injection like, implement the feature to set build-time variables.
- frontend: Register build args from application page.
- gitreceive: Inject build args before building Docker (web) image.

etcd key: `/paus/users/dtan4/rails-sample/build-args/FOO`
## TODO
- [x] paus-frontend https://github.com/dtan4/paus-frontend/pull/13
- [x] paus-gitreceive https://github.com/dtan4/paus-gitreceive/issues/21
## REF
- https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg
- [Easier builds and deployments using Git over HTTPS and OAuth](https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth)
- [Docker ARG がimage量産に便利 - Qiita](http://qiita.com/muddydixon/items/15e5fe8f04a0c325eb8e) (in Japanese)
- [Dockerfileのbuildで簡単にGithubのプライベートリポジトリをクローンする方法 - Qiita](http://qiita.com/Jah524/items/fa68f99c8b787f94b884) (in Japanese)
